services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXTERNAL_PORT}:5000
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/dodots_db
    # restart: unless-stopped
    # volumes:
      # - do-dots-data:/app/data
      #healthcheck:
      #test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/healthcheck"]
      #interval: 20s
      #timeout: 5s
      #retries: 3
      #start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:do-dots-dev.lloydery.org
      - traefik.port=5000
      - traefik.docker.network=web

  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dodots_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        #healthcheck:
        #test: [ "CMD-SHELL", "pg_isready -U postgres -d dodots_db" ]
        #interval: 1s
        #timeout: 5s
        #retries: 10

volumes:
  pgdata:

networks:
  web:
    external: true
